name: "Request PR Review"
description: "Request pull request review to reviewers periodically"
inputs:
  token:
    description: "github token"
    required: true
runs:
  using: node12
  main: index.js
